# Generated by Django 4.2.30 on 2026-08-01 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("embeddings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="chunk",
            name="chunk_emb_hnsw",
        ),
    ]
