# Generated by Django 4.2.30 on 2026-08-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("md", "0002_project"),
        ("md", "0002_remove_chunk_chunk_emb_hnsw"),
    ]

    operations = []
