# Generated by Django 5.2.17 on 2026-09-16 20:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("md", "0005_move_project_to_core"),
        ("routing", "0002_routingpolicy_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicySelection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "markdown",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_selection",
                        to="md.markdown",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selections",
                        to="routing.routingpolicy",
                    ),
                ),
            ],
        ),
    ]
